"""Refreshing stale extracts must not break resume.

`BuildAdminSet` skips any region already published. That is load-bearing: a set
of ~400 German Kreise converges across task retries only because each retry
skips what the last one finished. But it also meant a re-run over already-
published data published NOTHING — so the July sub-region extracts could never
be regenerated by re-running the job, which was the whole point of scheduling it.

The fix is staleness, not a boolean force: with refresh_after_days=7 a retry ten
minutes later still skips (those objects are minutes old) while a weekly run
rebuilds anything a week stale. A blunt force flag would make every retry
restart from zero.
"""
from osm_geocoder.handlers.planet import planet_handlers as ph

# key -> age in days
PUBLISHED = {
    "europe/germany/a": 0.007,    # ~10 minutes — this run just made it
    "europe/germany/b": 3.0,      # a few days
    "europe/germany/c": 32.0,     # the July vintage
}


def _skip(**kw):
    kw.setdefault("refresh_after_days", 0)
    kw.setdefault("force_refresh", False)
    return ph._regions_to_skip(PUBLISHED, **kw)


def test_default_preserves_the_old_behaviour():
    """0 = never refresh: everything published is skipped, as before."""
    assert _skip() == set(PUBLISHED)


def test_resume_still_works_under_a_refresh_window():
    """The point: a retry minutes later must NOT rebuild what it just made."""
    skip = _skip(refresh_after_days=7)
    assert "europe/germany/a" in skip, "a 10-minute-old extract must still be skipped"
    assert "europe/germany/b" in skip, "3 days is inside a 7-day window"


def test_stale_regions_are_rebuilt():
    skip = _skip(refresh_after_days=7)
    assert "europe/germany/c" not in skip, "a 32-day-old extract must be rebuilt"


def test_a_tighter_window_rebuilds_more():
    skip = _skip(refresh_after_days=1)
    assert skip == {"europe/germany/a"}, "only the sub-day one stays fresh"


def test_force_rebuilds_everything():
    assert _skip(force_refresh=True) == set()


def test_force_wins_over_the_window():
    assert _skip(refresh_after_days=365, force_refresh=True) == set()


def test_nothing_published_is_nothing_to_skip():
    assert ph._regions_to_skip({}, refresh_after_days=7, force_refresh=False) == set()


def test_ages_are_computed_from_last_modified():
    import datetime as dt

    now = dt.datetime.now(dt.timezone.utc)

    class _S3:
        def get_paginator(self, _):
            class P:
                def paginate(self, **kw):
                    return [{"Contents": [
                        {"Key": "europe/germany/x-latest.osm.pbf",
                         "LastModified": now - dt.timedelta(days=10)},
                        {"Key": "europe/germany/ignore.txt",
                         "LastModified": now},
                    ]}]
            return P()

    ages = ph._published_region_ages(_S3(), "b", "europe/germany")
    assert set(ages) == {"europe/germany/x"}, "only *-latest.osm.pbf counts"
    assert 9.9 < ages["europe/germany/x"] < 10.1
